name: Publish Caddy WebDAV Alpine Image

on:
  workflow_dispatch:
  schedule:
  - cron: "0 16 * * *"
  push:
    branches:
    - main

permissions:
  contents: read
  packages: write
  attestations: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: blazesnow
        password: ${{ secrets.TOKEN }}

    - name: Login to GitHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          blazesnow/caddy:webdav-alpine
          ghcr.io/blazesnow/caddy:webdav-alpine
